---
- name: Install Samba
   apt:
    name: samba
    state: present

- name: Create guest share directory
  file:
    path: "{{ samba_guest_share_path }}"
    state: directory

- name: Configure Samba
  lineinfile:
    path: /etc/samba/smb.conf
    line: |
      [{{ samba_guest_share_name }}]
      path = {{ samba_guest_share_path }}
      read only = yes
      guest ok = yes
      guest only = yes
      create mask = 0755
      directory mask = 0755
  notify:
    - restart samba

handlers:
  - name: restart samba
    service:
      name: smbd
      state: restarted